version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ${DB_PATH}:/data
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  moje_wydatki_api:
    depends_on:
      - db
    image: moje_wydatki_api:${APP_VERSION}
    ports:
      - "3001:80"
    restart: always
    environment:
      ALLOWED_USERS: ${ALLOWED_USERS}
      HTTP_PORT: 80
      API_PREFIX: /api
      CURRENCY: PLN
      DB_DIALECT: postgres
      DB_HOST: db
      DB_LOGGING: null
      DB_NAME: moje_wydatki
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      JWT_EXPIRES_IN: 15 minutes
      LOCALE: pl-PL
      NODE_ENV: prod
      ROOT_DIR: /app