version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ${DB_PATH}:/data
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  moje_wydatki_api:
    depends_on:
      - db
    image: moje_wydatki_api:${APP_VERSION}
    ports:
      - "3002:80"
    restart: always
    environment:
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      ALLOWED_USERS: ${ALLOWED_USERS}
      HTTP_PORT: 80
      API_PREFIX: ${API_PREFIX}
      CURRENCY: ${CURRENCY}
      DB_DIALECT: postgres
      DB_HOST: db
      DB_NAME: moje_wydatki_qa
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      LOCALE: ${LOCALE}
      NODE_ENV: qa
      ROOT_DIR: ${ROOT_DIR}
